name: toko_buku
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_launcher_icons: 0.9.3
  flutter_native_splash: 2.2.5
  flutter_screenutil: 5.5.3+2
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
  image_picker: 0.8.5+3
  firebase_storage: ^10.3.2
  cached_network_image: 3.2.1
  grouped_list: 5.1.2
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  image_path: assets/images/newLogo.png
  android: true
  ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/newSplash.png
  color_dark: "#121212"
  image_dark: assets/images/newSplash.png
  fullscreen: true

  android_12:
    image: assets/images/newSplash.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/newSplash.png
    icon_background_color_dark: "#121212"
    fullscreen: true
  web: false

flutter: 
  assets: 
    - assets/images/
    - assets/fonts/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
  uses-material-design: true

